# Generated by Django 5.2.7 on 2025-10-03 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('hostname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hostname')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC Address')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operating System')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Is Critical?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorOfCompromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(choices=[('IP', 'IP Address'), ('DOMAIN', 'Domain Name'), ('HASH', 'File Hash'), ('URL', 'URL')], max_length=10, verbose_name='IOC Type')),
                ('value', models.CharField(max_length=500, unique=True, verbose_name='Value')),
                ('source', models.CharField(blank=True, help_text='e.g., MISP, VirusTotal', max_length=100, null=True, verbose_name='Source')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Playbook Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=500, verbose_name='Target URL')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('description', models.TextField(verbose_name='Description')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10, verbose_name='Severity')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='NEW', max_length=20, verbose_name='Status')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP')),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Destination IP')),
                ('source_tool', models.CharField(help_text='e.g., Suricata, Wazuh, Splunk', max_length=100, verbose_name='Source Tool')),
                ('raw_log', models.JSONField(blank=True, null=True, verbose_name='Raw Log Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asset', verbose_name='Related Asset')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=500)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.alert')),
                ('playbook_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playbook')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('cve_id', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.JSONField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='core.scan')),
            ],
        ),
    ]
