# Generated by Django 5.2.7 on 2025-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='executable_path',
            field=models.CharField(blank=True, help_text="Full path to the tool's executable (e.g., /usr/bin/nmap). Leave blank if it's in the system's PATH.", max_length=255, null=True),
        ),
    ]
