# Generated by Django 5.2.7 on 2025-10-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vulnerability_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='is_playbook_scan',
            field=models.BooleanField(default=False, help_text='Was this scan initiated by a playbook?'),
        ),
    ]
