# Generated by Django 5.2.7 on 2025-10-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scan_is_playbook_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='eyewitness_report_path',
            field=models.CharField(blank=True, help_text='Path to the generated Eyewitness report', max_length=500, null=True),
        ),
    ]
