# Generated by Django 5.2.7 on 2025-10-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailtemplate_landingpage_phishingtarget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingresult',
            name='captured_geolocation',
            field=models.JSONField(blank=True, help_text='Stores latitude and longitude', null=True),
        ),
        migrations.AddField(
            model_name='phishingresult',
            name='captured_image_path',
            field=models.CharField(blank=True, help_text='Path to the captured webcam image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='phishingresult',
            name='captured_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phishingresult',
            name='captured_user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
