# Generated by Django 5.2.7 on 2025-10-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_phishingresult_captured_geolocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingtarget',
            name='telegram_user_id',
            field=models.CharField(blank=True, help_text="The target's numeric Telegram User ID", max_length=100, null=True),
        ),
    ]
