# Generated by Django 5.2.7 on 2025-10-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_phishingtarget_telegram_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='telegram_message',
            field=models.TextField(blank=True, help_text='Plain text message for Telegram. Use {{phishing_link}} and {{target_name}}.', null=True),
        ),
    ]
