# Generated by Django 5.2.7 on 2025-10-18 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APKAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apk_file', models.FileField(upload_to='apk_files/')),
                ('filename', models.CharField(max_length=255)),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APKFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='e.g., Dangerous Permission, Leaked Secret, Exported Component', max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ai_analysis', models.TextField(blank=True, help_text='AI-generated analysis of the finding', null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='apk_analyzer.apkanalysis')),
            ],
        ),
    ]
