# Generated by Django 5.2.7 on 2025-10-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkanalysis',
            name='fallback_activity',
            field=models.CharField(blank=True, help_text='Optional: specify fallback activity to launch if monkey fails (e.g., .LoginActivity)', max_length=255, null=True),
        ),
    ]
