# Generated by Django 5.2.7 on 2025-10-19 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('access_key_id', models.CharField(max_length=255)),
                ('secret_access_key', models.CharField(max_length=255)),
                ('default_region', models.CharField(default='us-east-1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloudScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='cloud_scanner.awsenvironment')),
            ],
        ),
        migrations.CreateModel(
            name='CloudFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('remediation', models.TextField()),
                ('details', models.JSONField()),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='cloud_scanner.cloudscan')),
            ],
        ),
    ]
