# Generated by Django 5.2.7 on 2025-10-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('mac_address', models.CharField(max_length=17, unique=True, verbose_name='MAC Address')),
                ('hostname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hostname')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Vendor')),
                ('open_ports', models.JSONField(blank=True, default=list, help_text='List of open ports and services discovered')),
                ('os_details', models.CharField(blank=True, help_text='Operating System details from Nmap', max_length=500, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WirelessNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', models.CharField(max_length=17, unique=True, verbose_name='BSSID (MAC Address)')),
                ('ssid', models.CharField(max_length=100, verbose_name='Network Name (SSID)')),
                ('encryption_type', models.CharField(blank=True, max_length=50, null=True)),
                ('channel', models.IntegerField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
